/*
 * This source file was generated by the Gradle 'init' task
 */
package gldailycode;

import java.util.HashMap;

import gldailycode.string.Leetcode_3;



public class Main {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Leetcode_3 leetcode3 = new Leetcode_3();
        leetcode3.lengthOfLongestSubstring("pwwkew");
    }
}
