/*
 * This source file was generated by the Gradle 'init' task
 */
package gldailycode;

import gldailycode.backtrack.Leetcode_78;
import gldailycode.binary_search.Leetcode_33;

public class Main {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        Leetcode_33 leetcode33 = new Leetcode_33();
        leetcode33.search(new int[]{1,3}, 3);
    }
}
